version: "3.8"

networks:
    domego:
        driver: bridge

services:
    # https://hub.docker.com/_/mongo
    mongo:
        image: mongo:latest
        restart: always
        volumes:
            - ./docker/config:/etc/mongo
            - ./docker/database:/data/db
        secrets:
            - db_root_password
        # entrypoint: ["mongod", "--config", "/etc/mongo/mongod.conf"]
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
            MONGO_INITDB_DATABASE: domego
        networks:
            - domego

    # https://github.com/FlorianLeChat/Domego
    node:
        image: domego
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000"]
            retries: 3
            timeout: 5s
        networks:
            - domego
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 512M
                reservations:
                    cpus: "0.25"
                    memory: 128M
            restart_policy:
                window: 60s
                condition: on-failure
                max_attempts: 5
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000

secrets:
    db_root_password:
        file: ./docker/config/db_root_password.txt